-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

SELECT CC.CAR_ID, CC.CAR_TYPE, FLOOR(CC.DAILY_FEE * 30 * (1 - CP.DISCOUNT_RATE * 0.01)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
         LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
                   ON CC.CAR_ID = CH.CAR_ID
         LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
                   ON CC.CAR_TYPE = CP.CAR_TYPE
WHERE CC.CAR_TYPE IN ('세단', 'SUV')
  AND CP.DURATION_TYPE LIKE '30일%'
GROUP BY CC.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
   AND (MAX(CH.END_DATE) < '2022-11-01' OR MAX(CH.END_DATE) IS NULL)
ORDER BY CC.DAILY_FEE DESC, CC.CAR_TYPE ASC, CC.CAR_ID DESC;