-- 조건에 맞는 도서 리스트 출력하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/144853

--- DDL
CREATE TABLE BOOK (
    BOOK_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT '도서 ID',
    CATEGORY VARCHAR(255) NOT NULL COMMENT '카테고리 (경제, 인문, 소설, 생활, 기술)',
    AUTHOR_ID INTEGER NOT NULL COMMENT '저자 ID',
    PRICE INTEGER NOT NULL COMMENT '판매가 (원)',
    PUBLISHED_DATE DATE NOT NULL COMMENT '출판일'
)
---

--- DML(INSERT)
INSERT INTO BOOK(CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE)
VALUES('인문', 1, 10000, '2020-01-01'),
('경제', 2, 9000, '2021-02-05'),
('인문', 2, 11000, '2021-04-11'),
('인문', 3, 10000, '2021-03-15'),
('생활', 1, 12000, '2021-01-10')
---

--- DML(SELECT)
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE LIKE '%2021-%' AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE ASC
---