-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/151139

SELECT
    MONTH, CAR_ID, RECORDS
FROM
    (SELECT
        MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(START_DATE) AS RECORDS, SUM(COUNT(START_DATE)) OVER (PARTITION BY CAR_ID) AS SUM_RECORDS
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY MONTH, CAR_ID
    ) AS CH
WHERE CH.SUM_RECORDS > 4
ORDER BY MONTH ASC, CAR_ID DESC;