-- 가장 비싼 상품 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131697

--- DDL
CREATE TABLE PRODUCT (
    PRODUCT_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_CODE VARCHAR(8) NOT NULL,
    PRICE INTEGER NOT NULL
);
---

--- DML(INSERT)
INSERT INTO PRODUCT(PRODUCT_CODE, PRICE)
VALUES('A1000001', 10000),
      ('A2000005', 9000),
      ('C1000006', 22000);
---

--- DML(SELECT)
SELECT MAX(PRICE) AS MAX_PRICE
FROM PRODUCT
---